#!/usr/bin/env node
/**
 * Checks the commits in a range against this project's two hard rules:
 *
 *  1. conventional commits — the release robot reads these to work out the
 *     next version number and to write the changelog, so a badly shaped
 *     subject line silently costs a release note;
 *  2. sole authorship — no co-signature and no mention of an AI tool, which
 *     is what makes the Git history usable as proof of authorship.
 *
 * Run it locally before pushing:
 *
 *     node scripts/check-commits.mjs origin/main..HEAD
 */

import { execFileSync } from "node:child_process";

/** Types the changelog understands. The first seven are the project's own. */
const TYPES = [
  "feat",
  "fix",
  "refactor",
  "docs",
  "test",
  "chore",
  "style",
  "perf",
  "build",
  "ci",
  "revert",
];

const HEADER = new RegExp(`^(${TYPES.join("|")})(\\([a-z0-9][a-z0-9._/-]*\\))?!?: .+`);
const MAX_HEADER_LENGTH = 100;

/** Anything that would claim someone, or something, else wrote the commit. */
const AUTHORSHIP_BANS = [
  { pattern: /co-authored-by\s*:/i, why: "carries a co-author trailer" },
  { pattern: /\bgenerated with\b/i, why: "mentions being generated by a tool" },
  {
    pattern: /\b(claude|chatgpt|gpt-[0-9]|copilot|codex|cursor\.sh|anthropic|openai)\b/i,
    why: "mentions an AI tool",
  },
  { pattern: /🤖/u, why: "carries a robot emoji" },
];

// A commit message contains newlines and spaces, so the fields are separated
// by the two control characters meant for exactly this.
const UNIT = "\u001f";
const RECORD = "\u001e";

function commitsIn(range) {
  const out = execFileSync("git", ["log", "--no-merges", "--format=%H%x1f%B%x1e", range], {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });

  return out
    .split(RECORD)
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0)
    .map((entry) => {
      const [hash = "", body = ""] = entry.split(UNIT);
      return { hash: hash.trim(), message: body.trim() };
    });
}

function problemsWith({ message }) {
  const problems = [];
  const header = message.split("\n")[0] ?? "";

  if (!HEADER.test(header)) {
    problems.push(
      `subject must read "type(scope): summary" — types: ${TYPES.join(", ")}`,
    );
  }
  if (header.length > MAX_HEADER_LENGTH) {
    problems.push(`subject is ${header.length} characters, the limit is ${MAX_HEADER_LENGTH}`);
  }
  for (const { pattern, why } of AUTHORSHIP_BANS) {
    if (pattern.test(message)) problems.push(`message ${why}`);
  }
  return problems;
}

const range = process.argv[2] ?? process.env["COMMIT_RANGE"] ?? "origin/main..HEAD";
const commits = commitsIn(range);

if (commits.length === 0) {
  console.log(`No commits to check in ${range}.`);
  process.exit(0);
}

let failed = 0;
for (const commit of commits) {
  const problems = problemsWith(commit);
  const subject = commit.message.split("\n")[0] ?? "";
  if (problems.length === 0) {
    console.log(`  ok   ${commit.hash.slice(0, 8)}  ${subject}`);
    continue;
  }
  failed += 1;
  console.log(`  FAIL ${commit.hash.slice(0, 8)}  ${subject}`);
  for (const problem of problems) console.log(`         → ${problem}`);
}

console.log(
  `\n${commits.length} commit(s) checked in ${range}, ${failed} rejected.`,
);
process.exit(failed === 0 ? 0 : 1);
